{
 "title": "JWT Pizza Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizzaRevenue_USD_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Pizza purchases/minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizzaSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchases"
    },
    {
     "expr": "rate(pizzaFailures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(requests_total{method=\"POST\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_total{method=\"GET\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_total{method=\"DELETE\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_total{method=\"PUT\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(serviceLatency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pizzaCreationLatency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(authAttempts_total{source=\"jwt-pizza-service\", result=\"success\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(authAttempts_total{source=\"jwt-pizza-service\", result=\"failure\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}